@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jul 22 22:07:12 -0400 2025
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim PDM_to_PCM_testbench_behav -key {Behavioral:sim_1:Functional:PDM_to_PCM_testbench} -tclbatch PDM_to_PCM_testbench.tcl -protoinst "protoinst_files/PDM_to_PCM.protoinst" -protoinst "protoinst_files/bd_5a83.protoinst" -protoinst "protoinst_files/bd_8523.protoinst" -protoinst "protoinst_files/bd_3885.protoinst" -view C:/Users/kuflu/Vivado/Research/FIFO-DMA/tb_mic_sampler_behav.wcfg -view C:/Users/kuflu/Vivado/Research/FIFO-DMA/PDM_to_PCM_testbench_behav.wcfg -log simulate.log"
call xsim  PDM_to_PCM_testbench_behav -key {Behavioral:sim_1:Functional:PDM_to_PCM_testbench} -tclbatch PDM_to_PCM_testbench.tcl -protoinst "protoinst_files/PDM_to_PCM.protoinst" -protoinst "protoinst_files/bd_5a83.protoinst" -protoinst "protoinst_files/bd_8523.protoinst" -protoinst "protoinst_files/bd_3885.protoinst" -view C:/Users/kuflu/Vivado/Research/FIFO-DMA/tb_mic_sampler_behav.wcfg -view C:/Users/kuflu/Vivado/Research/FIFO-DMA/PDM_to_PCM_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
