# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/mic_dma/ip/mic_dma_proc_sys_0_0/mic_dma_proc_sys_0_0.xci
# IP: The module: 'mic_dma_proc_sys_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/PDM_to_PCM.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM || ORIG_REF_NAME==PDM_to_PCM} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_PDM_reader_0_0/PDM_to_PCM_PDM_reader_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_PDM_reader_0_0 || ORIG_REF_NAME==PDM_to_PCM_PDM_reader_0_0} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_cic_compiler_0_0/PDM_to_PCM_cic_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_cic_compiler_0_0 || ORIG_REF_NAME==PDM_to_PCM_cic_compiler_0_0} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_0_0/PDM_to_PCM_fir_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_fir_compiler_0_0 || ORIG_REF_NAME==PDM_to_PCM_fir_compiler_0_0} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_cic_compiler_1_0/PDM_to_PCM_cic_compiler_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_cic_compiler_1_0 || ORIG_REF_NAME==PDM_to_PCM_cic_compiler_1_0} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_1_0/PDM_to_PCM_fir_compiler_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_fir_compiler_1_0 || ORIG_REF_NAME==PDM_to_PCM_fir_compiler_1_0} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_round_and_saturate_0_0/PDM_to_PCM_round_and_saturate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_round_and_saturate_0_0 || ORIG_REF_NAME==PDM_to_PCM_round_and_saturate_0_0} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_amplify_0_0/PDM_to_PCM_amplify_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_amplify_0_0 || ORIG_REF_NAME==PDM_to_PCM_amplify_0_0} -quiet] -quiet

# XDC: c:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/PDM_to_PCM/PDM_to_PCM_ooc.xdc

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/mic_dma/ip/mic_dma_proc_sys_0_0/mic_dma_proc_sys_0_0.xci
# IP: The module: 'mic_dma_proc_sys_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/PDM_to_PCM.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM || ORIG_REF_NAME==PDM_to_PCM} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_PDM_reader_0_0/PDM_to_PCM_PDM_reader_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_PDM_reader_0_0 || ORIG_REF_NAME==PDM_to_PCM_PDM_reader_0_0} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_cic_compiler_0_0/PDM_to_PCM_cic_compiler_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_cic_compiler_0_0 || ORIG_REF_NAME==PDM_to_PCM_cic_compiler_0_0} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_0_0/PDM_to_PCM_fir_compiler_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_fir_compiler_0_0 || ORIG_REF_NAME==PDM_to_PCM_fir_compiler_0_0} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_cic_compiler_1_0/PDM_to_PCM_cic_compiler_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_cic_compiler_1_0 || ORIG_REF_NAME==PDM_to_PCM_cic_compiler_1_0} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_1_0/PDM_to_PCM_fir_compiler_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_fir_compiler_1_0 || ORIG_REF_NAME==PDM_to_PCM_fir_compiler_1_0} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_round_and_saturate_0_0/PDM_to_PCM_round_and_saturate_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_round_and_saturate_0_0 || ORIG_REF_NAME==PDM_to_PCM_round_and_saturate_0_0} -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_amplify_0_0/PDM_to_PCM_amplify_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_amplify_0_0 || ORIG_REF_NAME==PDM_to_PCM_amplify_0_0} -quiet] -quiet

# XDC: c:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/PDM_to_PCM/PDM_to_PCM_ooc.xdc
