# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/mic_dma/ip/mic_dma_axi_mem_intercon_1_imp_auto_pc_0/mic_dma_axi_mem_intercon_1_imp_auto_pc_0.xci
# IP: The module: 'mic_dma_axi_mem_intercon_1_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma/ip/mic_dma_axi_mem_intercon_1_imp_auto_pc_0/mic_dma_axi_mem_intercon_1_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mic_dma_axi_mem_intercon_1_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/mic_dma/ip/mic_dma_axi_mem_intercon_1_imp_auto_pc_0/mic_dma_axi_mem_intercon_1_imp_auto_pc_0.xci
# IP: The module: 'mic_dma_axi_mem_intercon_1_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma/ip/mic_dma_axi_mem_intercon_1_imp_auto_pc_0/mic_dma_axi_mem_intercon_1_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mic_dma_axi_mem_intercon_1_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
