# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/mic_dma_ila_system_ila_0_0.xci
# IP: The module: 'mic_dma_ila_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/bd_3885.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3885 || ORIG_REF_NAME==bd_3885} -quiet] -quiet

# IP: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/ip/ip_0/bd_3885_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3885_ila_lib_0 || ORIG_REF_NAME==bd_3885_ila_lib_0} -quiet] -quiet

# IP: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/ip/ip_1/bd_3885_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3885_g_inst_0 || ORIG_REF_NAME==bd_3885_g_inst_0} -quiet] -quiet

# XDC: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3885_ila_lib_0 || ORIG_REF_NAME==bd_3885_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3885_ila_lib_0 || ORIG_REF_NAME==bd_3885_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/ip/ip_0/bd_3885_ila_lib_0_ooc.xdc

# XDC: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/bd_3885_ooc.xdc

# XDC: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/mic_dma_ila_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mic_dma_ila_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/mic_dma_ila_system_ila_0_0.xci
# IP: The module: 'mic_dma_ila_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/bd_3885.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3885 || ORIG_REF_NAME==bd_3885} -quiet] -quiet

# IP: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/ip/ip_0/bd_3885_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3885_ila_lib_0 || ORIG_REF_NAME==bd_3885_ila_lib_0} -quiet] -quiet

# IP: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/ip/ip_1/bd_3885_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3885_g_inst_0 || ORIG_REF_NAME==bd_3885_g_inst_0} -quiet] -quiet

# XDC: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3885_ila_lib_0 || ORIG_REF_NAME==bd_3885_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3885_ila_lib_0 || ORIG_REF_NAME==bd_3885_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/ip/ip_0/bd_3885_ila_lib_0_ooc.xdc

# XDC: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/bd_0/bd_3885_ooc.xdc

# XDC: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma_ila/ip/mic_dma_ila_system_ila_0_0/mic_dma_ila_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mic_dma_ila_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
