# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pynq-z2_v1.0.xdc/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/PDM_to_PCM/PDM_to_PCM.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM || ORIG_REF_NAME==PDM_to_PCM} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_PDM_reader_0_0/PDM_to_PCM_PDM_reader_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_PDM_reader_0_0 || ORIG_REF_NAME==PDM_to_PCM_PDM_reader_0_0} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_cic_compiler_0_0/PDM_to_PCM_cic_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_cic_compiler_0_0 || ORIG_REF_NAME==PDM_to_PCM_cic_compiler_0_0} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_0_0/PDM_to_PCM_fir_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_fir_compiler_0_0 || ORIG_REF_NAME==PDM_to_PCM_fir_compiler_0_0} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_cic_compiler_1_0/PDM_to_PCM_cic_compiler_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_cic_compiler_1_0 || ORIG_REF_NAME==PDM_to_PCM_cic_compiler_1_0} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_1_0/PDM_to_PCM_fir_compiler_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_fir_compiler_1_0 || ORIG_REF_NAME==PDM_to_PCM_fir_compiler_1_0} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_round_and_saturate_0_0/PDM_to_PCM_round_and_saturate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_round_and_saturate_0_0 || ORIG_REF_NAME==PDM_to_PCM_round_and_saturate_0_0} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_amplify_0_0/PDM_to_PCM_amplify_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_amplify_0_0 || ORIG_REF_NAME==PDM_to_PCM_amplify_0_0} -quiet] -quiet

# Block Designs: bd/mic_dma/mic_dma.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma || ORIG_REF_NAME==mic_dma} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_processing_system7_0_0/mic_dma_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_processing_system7_0_0 || ORIG_REF_NAME==mic_dma_processing_system7_0_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_dma_0/mic_dma_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_dma_0 || ORIG_REF_NAME==mic_dma_dma_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_axi_smc_0/mic_dma_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_axi_smc_0 || ORIG_REF_NAME==mic_dma_axi_smc_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_rst_ps7_0_100M_0/mic_dma_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_rst_ps7_0_100M_0 || ORIG_REF_NAME==mic_dma_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_axi_mem_intercon_imp_auto_pc_0/mic_dma_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==mic_dma_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_axi_mem_intercon_0/mic_dma_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_axi_mem_intercon_0 || ORIG_REF_NAME==mic_dma_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_axi_mem_intercon_1_imp_auto_pc_0/mic_dma_axi_mem_intercon_1_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_axi_mem_intercon_1_imp_auto_pc_0 || ORIG_REF_NAME==mic_dma_axi_mem_intercon_1_imp_auto_pc_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_axi_mem_intercon_1_0/mic_dma_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_axi_mem_intercon_1_0 || ORIG_REF_NAME==mic_dma_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_fifo_generator_0_0/mic_dma_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_fifo_generator_0_0 || ORIG_REF_NAME==mic_dma_fifo_generator_0_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_clk_wiz_0_0/mic_dma_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_clk_wiz_0_0 || ORIG_REF_NAME==mic_dma_clk_wiz_0_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_clk_div_0_0/mic_dma_clk_div_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_clk_div_0_0 || ORIG_REF_NAME==mic_dma_clk_div_0_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_proc_sys_0_0/mic_dma_proc_sys_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_proc_sys_0_0 || ORIG_REF_NAME==mic_dma_proc_sys_0_0} -quiet] -quiet

# Block Designs: bd/PDM_to_PCM/PDM_to_PCM.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM || ORIG_REF_NAME==PDM_to_PCM} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_PDM_reader_0_0/PDM_to_PCM_PDM_reader_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_PDM_reader_0_0 || ORIG_REF_NAME==PDM_to_PCM_PDM_reader_0_0} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_cic_compiler_0_0/PDM_to_PCM_cic_compiler_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_cic_compiler_0_0 || ORIG_REF_NAME==PDM_to_PCM_cic_compiler_0_0} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_0_0/PDM_to_PCM_fir_compiler_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_fir_compiler_0_0 || ORIG_REF_NAME==PDM_to_PCM_fir_compiler_0_0} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_cic_compiler_1_0/PDM_to_PCM_cic_compiler_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_cic_compiler_1_0 || ORIG_REF_NAME==PDM_to_PCM_cic_compiler_1_0} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_1_0/PDM_to_PCM_fir_compiler_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_fir_compiler_1_0 || ORIG_REF_NAME==PDM_to_PCM_fir_compiler_1_0} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_round_and_saturate_0_0/PDM_to_PCM_round_and_saturate_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_round_and_saturate_0_0 || ORIG_REF_NAME==PDM_to_PCM_round_and_saturate_0_0} -quiet] -quiet

# IP: bd/PDM_to_PCM/ip/PDM_to_PCM_amplify_0_0/PDM_to_PCM_amplify_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PDM_to_PCM_amplify_0_0 || ORIG_REF_NAME==PDM_to_PCM_amplify_0_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_mic_sampler_0_0/mic_dma_mic_sampler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_mic_sampler_0_0 || ORIG_REF_NAME==mic_dma_mic_sampler_0_0} -quiet] -quiet

# XDC: c:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/PDM_to_PCM/PDM_to_PCM_ooc.xdc

# XDC: c:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/PDM_to_PCM/PDM_to_PCM_ooc.xdc

# XDC: c:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma/mic_dma_ooc.xdc
