# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/mic_dma/mic_dma.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma || ORIG_REF_NAME==mic_dma} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_processing_system7_0_0/mic_dma_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_processing_system7_0_0 || ORIG_REF_NAME==mic_dma_processing_system7_0_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_dma_0/mic_dma_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_dma_0 || ORIG_REF_NAME==mic_dma_dma_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_axi_smc_0/mic_dma_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_axi_smc_0 || ORIG_REF_NAME==mic_dma_axi_smc_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_rst_ps7_0_100M_0/mic_dma_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_rst_ps7_0_100M_0 || ORIG_REF_NAME==mic_dma_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_axi_mem_intercon_0/mic_dma_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_axi_mem_intercon_0 || ORIG_REF_NAME==mic_dma_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_axi_mem_intercon_1_0/mic_dma_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_axi_mem_intercon_1_0 || ORIG_REF_NAME==mic_dma_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_axis_data_fifo_0_0/mic_dma_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_axis_data_fifo_0_0 || ORIG_REF_NAME==mic_dma_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_mic_sampler_0_0/mic_dma_mic_sampler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_mic_sampler_0_0 || ORIG_REF_NAME==mic_dma_mic_sampler_0_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_system_ila_0_0/mic_dma_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_system_ila_0_0 || ORIG_REF_NAME==mic_dma_system_ila_0_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_axi_mem_intercon_imp_auto_pc_0/mic_dma_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==mic_dma_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/mic_dma/ip/mic_dma_axi_mem_intercon_1_imp_auto_pc_0/mic_dma_axi_mem_intercon_1_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mic_dma_axi_mem_intercon_1_imp_auto_pc_0 || ORIG_REF_NAME==mic_dma_axi_mem_intercon_1_imp_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/dkuflu/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/mic_dma/mic_dma_ooc.xdc
