# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_1_0/PDM_to_PCM_fir_compiler_1_0.xci
# IP: The module: 'PDM_to_PCM_fir_compiler_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'PDM_to_PCM_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_1_0/PDM_to_PCM_fir_compiler_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PDM_to_PCM_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.srcs/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_1_0/PDM_to_PCM_fir_compiler_1_0.xci
# IP: The module: 'PDM_to_PCM_fir_compiler_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'PDM_to_PCM_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/kuflu/Vivado/Research/FIFO-DMA/FIFO-DMA.gen/sources_1/bd/PDM_to_PCM/ip/PDM_to_PCM_fir_compiler_1_0/PDM_to_PCM_fir_compiler_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PDM_to_PCM_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
